Terraform 1
Otus-DevOps-2017-11/asamoylov_infra pull request #4
Opened 2018-01-08 17:57 UTC by Drenjy

2018-01-11 19:40 UTC, Nklya requested changes
Описание PR нужно заполнять

2018-01-11 19:42 UTC, Nklya commented
И заполни пожалуйста профиль на гитхабе полностью.

2018-01-15 17:52 UTC, Nklya commented
И настрой гит чтобы коммиты нормальные были, а не это серое непонятно что
<img width="680" alt="screen shot 2018-01-15 at 20 52 27" src="https://user-images.githubusercontent.com/26086394/34955549-07f1273e-fa36-11e7-9998-8cc7fb938fec.png">

2018-01-22 17:43 UTC, Nklya commented
Описание PR это здесь.
<img width="726" alt="screen shot 2018-01-22 at 20 43 30" src="https://user-images.githubusercontent.com/26086394/35235340-eea9060a-ffb4-11e7-9c6e-1ccd0620a235.png">

2018-01-24 21:46 UTC, Nklya requested changes
Смержил мастер в эту ветку и вычистил дичь за тебя.
 
Теперь почти все ок, **тебе** нужно вернуть параметризацию параметров в пакере для проекта и исходного образа.



Следующие ДЗ сдаешь по схеме:
1. Создаешь ветку от мастера.
2. Выполняешь задания
3. Делаешь PR и **ждешь** проверки его.
4. Когда проверен, мержишь в мастер и продолжаешь с пункта 1 следующее ДЗ, если ты не умеешь рабоать с Git.

2018-01-29 18:19 UTC, Drenjy commented
Домашняя работа № 8. Выполнено основного задания и задания с одной звёздочкой.

2018-01-30 12:11 UTC, Nklya approved these changes
Добрый день.

Андрей, теперь все относительно нормально.
Условия дз выполнены.

2018-01-31 15:25 UTC, merged